### ISSUE TITLE
exception on loading config

### ISSUE THREAD

**Issue by marcin001** [apexad/homebridge-eufy-robovac#10]
(node:1696) UnhandledPromiseRejectionWarning: TypeError: Key is missing or incorrect.
    at new t.exports (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/node_modules/eufy-robovac/dist/index.js:1:13622)
    at new t (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/node_modules/eufy-robovac/dist/index.js:1:5798)
    at t.<anonymous> (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/src/index.ts:80:18)
    at /usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/webpack/bootstrap:83:1
    at Object.next (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/webpack/bootstrap:83:1)
    at /usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/webpack/bootstrap:83:1
    at new Promise (<anonymous>)
    at r (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/webpack/bootstrap:83:1)
    at t.setup (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/src/index.ts:79:2)
    at new t (/usr/lib/node_modules/homebridge-eufy-robovac/dist/webpack:/src/index.ts:76:8)
    at /usr/lib/node_modules/homebridge/src/server.ts:356:50
    at Array.forEach (<anonymous>)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/src/server.ts:329:29)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:155:12)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
(node:1696) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1696) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by apexad** [comment]
It's un-clear where this error was coming from.

However, as of this writing, IP address is no longer supported (README will be updated shortly).  You need to use `deviceId`, so your config.json `accessories' block needs to have an entry that looks like this:

```json
{
  "accessory": "Eufy RoboVac",
  "name": "Vacuum Cleaner",
  "deviceId": "<your devId>",
  "localKey": "<your localKey>"
},
```

Instructions to get `devId` (called `deviceId` in the plugin config) and `localKey` are [here](https://github.com/joshstrange/eufy-robovac)
Sometime today, I will be adding a config.schema.json to the plugin so that it can be setup use the homebridge-ui.  May also look into making getting `deviceId` and `localKey` a bit easier.

If you are confident your config.json is setup correctly an this plugin is still not working, please re-open this issue.

**Comment by marcin001** [comment]
Hi,

I guess i grabbed the wrong lockey.  For whatever reason logcat does not
return the search string you provided in the instructions.  any clues
there?  I've tried various strings that appeared to be lockey's in the adb
log but not having much luck...

**Comment by apexad** [comment]
> Hi, I guess i grabbed the wrong lockey. For whatever reason logcat does not return the search string you provided in the instructions. any clues there? I've tried various strings that appeared to be lockey's in the adb log but not having much luck...
> […](#)

You may have to install EufyHome 2.3.2 via apk since it seems new versions no longer output the information.
