### ISSUE TITLE
Robovac Error Disconnected

### ISSUE THREAD

**Issue by rfitzpatrickCO** [apexad/homebridge-eufy-robovac#30]
I continue to get the error below. Any help troubleshooting this would be appreciated.

```
Looking for device...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Connecting...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Connecting...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Connecting...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
Connecting...
Robovac Error {}
Robovac Error {}
Robovac Error {}
Disconnected!
Disconnected!
Disconnected!
Disconnected!
```

**Comment by fiigo0** [comment]
Same issue here, 

```
Hardware
Eufy 30C
Wi-Fi version 1.1.5
MCU version 1.1.6
```

I restarted the vacuum, reinstall the plugin and set the keys and restarted homebridge it worked one time from the home app but after it went to charge station stoped working, i also have a static ip for the vacuum 

```
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /usr/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Connecting...
Robovac Error {}
Disconnected!
Looking for device...
Looking for device...
Found device <deviceId> at 10.0.1.102
Connecting...
Found device <deviceId> at 10.0.1.102
Connecting...
Connected!
Connected!
Robovac Error {}
Disconnected!
```

**Comment by coneybeare** [comment]
Seeing the same issue. I redid configuration (`deviceId` and `localKey` did not change on device), and plugin still cannot connect to the robovac:

````
 npm run demo 816[REDACTED]d5c c1f[REDACTED]680 status

> eufy-robovac@1.4.3 demo
> node demo.js "816[REDACTED]d5c" "c1f[REDACTED]680" "status"

Looking for device...
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /Users/[REDACTED]/Code/eufy-robovac/node_modules/tuyapi/index.js:619:13
    at Timeout._onTimeout (/Users/[REDACTED]/Code/eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)
Connecting...
Robovac Error {}
Disconnected!
````

**Comment by Kris8768** [comment]
Im also getting the same issue. Seemed to work great for about a week but then it started to just show updating in Home app and looks to be causing other Homebridge devices to be delayed / updating. I have re-installed home bridge but this is still the same. Also set static IP and forced it to that IP within my DHCP to ensure it stays and nothing else uses it.

Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /homebridge/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /homebridge/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)

Has anyone else found a solution to this?

**Comment by xnonim** [comment]
I'm having same issue, but waiting for maybe 2 minutes, it fixes itself. sometimes I have to push the switch in home app many times, and it works.

**Comment by MonsterEnergy-wtf** [comment]
From my side I restart Homebridge every 15 minutes via cron. This resolves the issue. Definitely not ideal but working.

**Comment by ole-gitty** [comment]
Was just trying to get this plugin working for the first time, and I am having the same issue - "find() timeout" and then "Robovac Error". I have extracted the keys properly so I know it's not just me.  This is on a 30C.

**Comment by apexad** [comment]
So at this time I am going to close this issue as it seems intermittent at best and otherwise related to the 'slowness' of the way the plugin is polling status (and setting it for that matter) which is generally covered by what Homebridge 1.3.x is reporting and #34 calls this out better.

Assuming device id and local id are correct and you do not have the Eufy Home app open on any other device, this plugin should still be working, but as mentioned in #34 I have yet to find the time to attempt to make this plugin respond faster and maintain a reliable connection.  If and when I do find some time I don't want to have to update 2 issues so instead watch #34 for updates (or if you actually see plugin version go up).

Lastly, me and others are looking into connecting to the vacuum using username/password, please see https://github.com/apexad/eufy-robovac/issues/14 (on the main library not the homebridge plugin).
