### ISSUE TITLE
Plugin dows down Homebridge, characteristics slow/fail to respond & unhandled promise rejections

### ISSUE THREAD

**Issue by RosemaryOrchard** [apexad/homebridge-eufy-robovac#33]
I just updated my HomeBridge to v1.3.0, and these entries now appear in the log file when HomeBridge starts: 

```
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[date, time] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Motion Detected' was slow to respond! See https://git.io/JtMGR for more info.
(node:20736) UnhandledPromiseRejectionWarning: Error: connection timed out
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:303:18)
    at Object.onceWrapper (events.js:420:28)
    at Socket.emit (events.js:314:20)
    at Socket._onTimeout (net.js:483:8)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
(node:20736) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:20736) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[date, time][homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[date, time][homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[date, time][homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[date, time][homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Motion Detected' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
```

**Comment by xnonim** [comment]
same here, it would be sad if this great plug-in is no longer maintained

[2/17/2021, 11:13:31 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://git.io/JtMGR for more info.
[2/17/2021, 11:13:31 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' was slow to respond! See https://git.io/JtMGR for more info.
[2/17/2021, 11:13:31 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' was slow to respond! See https://git.io/JtMGR for more info.
[2/17/2021, 11:13:31 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' was slow to respond! See https://git.io/JtMGR for more info.

[2/17/2021, 11:15:09 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/17/2021, 11:15:09 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Status Low Battery' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/17/2021, 11:15:09 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Battery Level' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.
[2/17/2021, 11:15:09 AM] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'Charging State' didn't respond at all!. Please check that you properly call the callback! See https://git.io/JtMGR for more info.

**Comment by apexad** [comment]
I'm planning on putting on some work on this plugin soon.
Closing in favor of #30
