### ISSUE TITLE
Battery Status Not Displayed

### ISSUE THREAD

**Issue by HenryGelderbloem** [apexad/homebridge-eufy-robovac#53]
I am not getting the Battery Level or Charging State in the Home app.

I can see that it correctly polls my RoboVac:

Data from device: {
  dps: {
    '2': false,
    '5': 'Nosweep',
    '15': 'Charging',
    '101': true,
    '102': 'Max',
    '104': 76,
    '106': 0,
    '107': false,
    '109': 0,
    '110': 0,
    '122': 'Nosweep',
    '131': false,
    '132': 2504,
    '133': 24,
    '134': 1,
    '137': 0,
    '140': '0070000024025042504'
  }
}

I am not getting any obvious errors in the log with debugging logs enabled.

I do get this when restarting the plugin:

Error: find() timed out. Is the device powered on and the ID or IP correct?
    at /var/lib/homebridge/node_modules/homebridge-eufy-robovac/node_modules/tuyapi/index.js:622:13
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-eufy-robovac/node_modules/p-timeout/index.js:25:13)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)
Connecting...
Robovac Error {}
Disconnected!

I also get:

[10/02/2024, 13:33:57] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[10/02/2024, 13:34:03] [homebridge-eufy-robovac] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

**Comment by leolelego** [comment]
Apparently @HenryGelderbloem it was removed. See this comment. That’s too bad ..
https://github.com/apexad/homebridge-eufy-robovac/issues/45#issuecomment-1434615612
